FROM ruby:2.2
RUN apt update -qq && apt install -y build-essential

ENV APP_HOME /app
RUN mkdir $APP_HOME

WORKDIR $APP_HOME
COPY Gemfile* $APP_HOME/
RUN bundle install
COPY . $APP_HOME

ENV POST_SERVICE_HOST post_myal
ENV POST_SERVICE_PORT 5000
ENV COMMENT_SERVICE_HOST comment_myal
ENV COMMENT_SERVICE_PORT 9292

CMD ["puma"]
