FROM alpine:3.7

ENV POST_SERVICE_HOST post_myal
ENV POST_SERVICE_PORT 5000
ENV COMMENT_SERVICE_HOST comment_myal
ENV COMMENT_SERVICE_PORT 9292
ENV APP_HOME /app

RUN apk update && apk upgrade && \
    apk --no-cache add ruby ruby-dev build-base && \
    gem install bundler --no-ri --no-rdoc

wORKDIR $APP_HOME
COPY . $APP_HOME

RUN bundle install


CMD ["puma"]
