global:
  slack_api_url: 'https://hooks.slack.com/services/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'

route:
  receiver: 'slack-notifications'

receivers:
- name: 'slack-notifications'
  slack_configs:
  - channel: '#alertingservice'
