version: '3.3'
services:
  post_db:
    image: mongo:3.2
    volumes:
      - post_db:/data/db
    networks:
      back_net:
        ipv4_address: 10.0.2.2
  ui:
    build: ../src/ui
    image: ${USERNAME}/ui:${SERVVER}
    ports:
      - 9292:9292/tcp
    networks:
      front_net:
        ipv4_address: 10.0.1.3
  post:
    build: ../src/post-py
    image: ${USERNAME}/post:${SERVVER}
    networks:
      back_net:
        ipv4_address: 10.0.2.4
      front_net:
        ipv4_address: 10.0.1.4
  comment:
    build: ../src/comment
    image: ${USERNAME}/comment:${SERVVER}
    networks:
      back_net:
        ipv4_address: 10.0.2.5
      front_net:
        ipv4_address: 10.0.1.5
  prometheus:
    image: ${USERNAME}/prometheus
    ports:
      - '9090:9090'
    volumes:
      - prometheus_data:/prometheus
    command: # Передаем доп параметры в командной строке
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention=1d' # Задаем время хранения метрик в 1 день
    networks:
      back_net:
        ipv4_address: 10.0.2.6
      front_net:
        ipv4_address: 10.0.1.6


volumes:
  post_db:
  prometheus_data:

networks:
  back_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: ${BACKNET}
  front_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: ${FRONTNET}
