version: '3.3'
services:
  post_db:
    image: mongo:3.2
    volumes:
      - post_db:/data/db
    networks:
      back_net:
        ipv4_address: 10.0.2.2
  ui:
    build: ../src/ui
    image: ${USERNAME}/ui:${SERVVER}
    ports:
      - 9292:9292/tcp
    networks:
      front_net:
        ipv4_address: 10.0.1.3
  post:
    build: ../src/post-py
    image: ${USERNAME}/post:${SERVVER}
    networks:
      back_net:
        ipv4_address: 10.0.2.4
      front_net:
        ipv4_address: 10.0.1.4
  comment:
    build: ../src/comment
    image: ${USERNAME}/comment:${SERVVER}
    networks:
      back_net:
        ipv4_address: 10.0.2.5
      front_net:
        ipv4_address: 10.0.1.5
  prometheus:
    image: ${USERNAME}/prometheus
    ports:
      - '9090:9090'
    volumes:
      - prometheus_data:/prometheus
    command: # Передаем доп параметры в командной строке
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention=1d' # Задаем время хранения метрик в 1 день
    networks:
      back_net:
        ipv4_address: 10.0.2.6
      front_net:
        ipv4_address: 10.0.1.6
  
  node-exporter:
    image: prom/node-exporter:v0.15.2
    user: root
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points="^/(sys|proc|dev|host|etc)($$|/)"'
    networks:
      back_net:
        ipv4_address: 10.0.2.7
      front_net:
        ipv4_address: 10.0.1.7

  mongodb-exporter:
    image: bitnami/mongodb-exporter:latest
    command:
      - '--mongodb.uri=mongodb://post_db:27017'
    networks:
      back_net:
        ipv4_address: 10.0.2.8
      front_net:
        ipv4_address: 10.0.1.8
  blackboxexporter:
    image: ${USERNAME}/blackboxexporter
    ports:
      - '9115:9115'
    networks:
      back_net:
        ipv4_address: 10.0.2.9
      front_net:
        ipv4_address: 10.0.1.9

volumes:
  post_db:
  prometheus_data:

networks:
  back_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: ${BACKNET}
  front_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: ${FRONTNET}
