---
version: '3.3'
services:
  post_db:
    image: mongo:3.2
    volumes:
      - post_db:/data/db
    networks:
      back_net:
  ui:
    build: ./ui
    image: ${USERNAME}/ui:${SERVVER}
    ports:
      - 9292:9292/tcp
    networks:
      front_net:
  post:
    build: ./post-py
    image: ${USERNAME}/post:${SERVVER}
    networks:
      back_net:
      front_net:
  comment:
    build: ./comment
    image: ${USERNAME}/comment:${SERVVER}
    networks:
      back_net:
      front_net:

volumes:
  post_db:

networks:
  back_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: ${BACKNET}
  front_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: ${FRONTNET}
